{% set name = "yatiml" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4761a9da7f3e95e80eccedd24e64326962c63394c7bd4703a1f3122cebdccc79

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python >=3.7
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pyyaml >=5.1,!=5.4.1
    - typing_extensions

test:
  imports:
    - {{ name }}
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/yatiml/yatiml
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "Reading, checking and writing YAML from Python"

extra:
  recipe-maintainers:
    - LourensVeen
